[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security: max-age=63072000; includeSubDomains; preload
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = '''
      font-src 'self' fonts.gstatic.com gstatic.com *.gstatic.com;
      img-src 'self' data: *.shrinath.me;
      script-src 'self' 'unsafe-inline' *.google-analytics.com *.googletagmanager.com;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      object-src 'none'
    '''